---
- name: Login to OCP and Get  Project
  command: "{{ item }}"
  with_items:
    - "{{ OC_HOME}}/oc login -u openshift-dev -p devel"
    - "{{OC_HOME}}/oc project {{ GIT_SOURCE_PROJECT }}"

- name: Create HOTEL App
  shell: "{{ OC_HOME }}/oc new-app {{HOTELS_GIT_REPO}} --image-stream=php --context-dir={{HOTELS_GIT_REPO_CONTEXT}} --name={{HOTELS_APP_NAME}} -l app={{HOTELS_APP_NAME}}"

- name: expose service
  shell: "{{ OC_HOME }}/oc expose svc {{HOTELS_APP_NAME}}"


