---
- name: Login to OCP and Get  Project
  command: "{{ item }}"
  with_items:
    - "{{ OC_LOC}} login -u openshift-dev -p devel"
    - "{{OC_LOC}} project {{ GIT_SOURCE_PROJECT }}"

- name: Create HOTEL App
  shell: "{{ OC_LOC }} new-app {{HOTELS_GIT_REPO}} --image-stream=php --context-dir={{HOTELS_GIT_REPO_CONTEXT}} --name={{HOTELS_APP_NAME}} -l app={{HOTELS_APP_NAME}}"

- name: expose service
  shell: "{{ OC_LOC }} expose svc {{HOTELS_APP_NAME}}"


